services:
  - type: web
    name: livora-ksa
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd website && gunicorn website.wsgi:application"
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.13.2"
