# Generated by Django 3.1.12 on 2025-06-07 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_healthreport_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('allergies', models.CharField(blank=True, max_length=255)),
                ('other_issues', models.TextField(blank=True)),
                ('insurance', models.CharField(blank=True, max_length=100)),
                ('insurance_start', models.DateField(blank=True, null=True)),
                ('insurance_end', models.DateField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('emergency_name', models.CharField(blank=True, max_length=100)),
                ('emergency_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('clinic_name', models.CharField(blank=True, max_length=100)),
                ('doctor_name', models.CharField(blank=True, max_length=100)),
                ('clinic_phone', models.CharField(blank=True, max_length=20)),
                ('clinic_address', models.TextField(blank=True)),
                ('clinic_reason', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='healthreport',
            name='nurse_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='nurse_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='main.medicalhistory')),
            ],
        ),
    ]
